### ISSUE TITLE
ResponseReplayInfo: replay info contains an error: 2

### ISSUE THREAD

**Issue by magsol** [aiarena/SC2AutoObserver#3]
I've built SC2AutoObserver on macOS 11.1 Big Sur but am having trouble getting the replays to work.

It took some doing, but I installed cmake and googletest via brew, which compiled and built the project just fine (a few warnings) without needing Xcode.

I was then able to point SC2 to a replay generated by [aiarena](https://github.com/aiarena/aiarena-docker) and a custom ladder map, installed at the location provided in the SC2AutoObserver `README`.

The tricky part was installing the old version (4.10) of the SC2 client--I had to watch the replay through the official SC2 platform, allowing it to download the old client before I could provide this information to SC2AutoObserver.

However, this is the output I received:

```
> ./Observer -p replays/1_basic_bot_vs_loser_bot.SC2Replay \
    -- -d "B89B5D6FA7CBF6452E721311BFBC6CB2" \
    -e /Applications/StarCraft\ II/Versions/Base75689/SC2.app/Contents/MacOS/SC2

Using default speed: 4x
Using default delay: 3000ms
Launched SC2 (/Applications/StarCraft II/Versions/Base75689/SC2.app/Contents/MacOS/SC2), PID: 2671
Waiting for connection........
Connected to 127.0.0.1:8167
ResponseReplayInfo: replay info contains an error: 2
```

The SC2 game windows disappear and this message is displayed in the Terminal. I don't know how to troubleshoot this as there are no log files generated and I can't seem to find this error message in the SC2AutoObserver source code, suggesting the error is probably originating further up the stack somewhere in cpp-sc2.

I should note that I also **did not generate the hash myself**, but instead used the one specified in the `README`. I am unsure how to generate this hash myself.

Any suggestions would be greatly appreciated.

**Comment by alkurbatov** [comment]
Hi, @magsol 
you don't have to install old sc2 version, if you use the -d option and this might be the reason. This code was tested against the latest game client, which by some reason (perhaps for compatibility) contains the required binary used in the example.

**Comment by magsol** [comment]
Ok, to clarify: I can use the latest SC2 game client (for me, that's `/Applications/StarCraft II/Versions/Base83830`) but still specify the -d option? What value do I provide the -d argument?

**Comment by alkurbatov** [comment]
By providing the -d option you tell the c++ API which version of the game client you want to use (this hash value is some 4.10 version). Without it you can't use the new clients.
In case you use exactly the same client as it was used for recording a replay, the option is not needed.

**Comment by magsol** [comment]
Ah, ok. So since the replay was recorded using 4.10, but is _playing_ using the most current client, I'll need to use the -d option--and only that option, no need for -e.

But again, what hash value do I provide -d? The same one used in the README and the original post?

**Comment by alkurbatov** [comment]
I am not sure that you can safely omit -e, at least it didn't work for me on my mac. 

>But again, what hash value do I provide -d? The same one used in the README and the original post?

Yes, please, use the same value. The actual map can be found e.g. here:
https://github.com/Blizzard/s2client-proto/blob/63615821fad543d570d65f8d7ab67f71f33cf663/buildinfo/versions.json

**Comment by magsol** [comment]
Oh wow, had no idea that existed, but it makes sense. Thank you!!

What are the different hashes used for? It looks like `data-hash` is the one specified in this repo's README and in my original post above, but are the other hashes needed for anything?

On a different note: using the hash from the README (4.10 data-hash) and the executable for my current game client, I saw the client launch, but it crashed with this new error:

```Using default speed: 4x
Using default delay: 3000ms
Launched SC2 (/Applications/StarCraft II/Versions/Base83830/SC2.app/Contents/MacOS/SC2), PID: 4840
Waiting for connection.............
Connected to 127.0.0.1:8167
ResponseReplayInfo: replay info contains an error: 5
ResponseReplayInfo: error details: Required files of replay build version are not available.
```

My first guess would be that I need the old client, but if that's not the case, then I'm not sure what "files of replay build version" is referring to. Map files?

**Comment by alkurbatov** [comment]
>What are the different hashes used for? 

Unfortunately I don't know. The client accepts `data-hash`, the rest could be an internal thing.

>My first guess would be that I need the old client, but if that's not the case, then I'm not sure what "files of replay build version" is referring to. Map files?

Hard to say, could be maps, could be something else. I bet it can't launch with this hash on this client, but there is no clue.
These vague errors are thrown by the client.

**Comment by magsol** [comment]
Well, this is certainly strange.

I ran exactly the same command as in the original post, and this time it worked just fine.

I've no idea what changed.

**Comment by magsol** [comment]
I'll close for now, until and if I get more information about this issue.
